#! /bin/sh



bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          0 #12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#607d8b"
#bspc config focused_border_color "#122129"
bspc config normal_border_color "#2E3440"

# Handles Keys
sxhkd &

# Power Manager
xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
nitrogen --restore &
#~/bin/blur-background.sh &

# Enables Windows Key
ksuperkey &

# Compositor
picom &

# Polybar
~/.config/polybar/launch.sh &

# Wallpaper
# bwall -cup_dark &

# Network Manager
# nm-applet &

# handles cursor problem
xsetroot -cursor_name left_ptr &
